### ISSUE TITLE
Support elementDimensions Output Prop

### ISSUE THREAD

**Issue by ethanselzer** [ethanselzer/react-cursor-position#7]
### Tasks
* [x] Update code and tests
* [x] Update README.md
* [x] Update example site
* [x] Update CodePen example (post release)

### Notes
Output data structure shape should be:
```
{
    elementDimensions: {
        width: Number,
        height: Number
    }
    isActive: Boolean,
    isPositionOutside: Boolean,
    position: {
        x: Number,
        y: Number
    }
}
```

**Comment by ethanselzer** [comment]
Closing with #8
